# Generated by Django 4.0.3 on 2022-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I hated it'), (2, 'I didnt like it'), (3, 'it was ok'), (4, 'I liked it'), (5, 'I loved it')], null=True),
        ),
    ]
